<?php

namespace Modules\Common\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Common\Contracts\Cacheable;
use Modules\Common\Models\AppSetting;

class SeoTableSeeder extends Seeder
{
    use Cacheable;

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach (self::data() as $setting) {
            $this->updateCache($setting['key'], $setting['value']);
        }

        AppSetting::insert(self::data());
    }

    /**
     * Generate seo datas
     *
     * @return array
     */
    public function data()
    {
        return [
            /**
             * Common
             */
            // Beranda
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_beranda',
                'value' => 'Online Course',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_beranda',
                'value' => 'Gabung dengan SOC Media Academy sekarang untuk memulai karir online! Kami menawarkan pengetahuan berharga kepada siswa baru, profesional, dan karyawan yang ingin beradaptasi dengan dunia digital.',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_beranda',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_beranda',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Tentang Kami
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_tentang_kami',
                'value' => 'Tentang Kami',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_tentang_kami',
                'value' => 'Transformasikan karirmu dengan platform online course kami di SOC Media Academy, bagian dari SOC Media Group. Bergabunglah sekarang untuk sukses dalam dunia digital!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_tentang_kami',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_tentang_kami',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Hubungi Kami
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_hubungi_kami',
                'value' => 'Hubungi  Kami',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_hubungi_kami',
                'value' => 'Jangan ragu untuk menghubungi SOC Media Academy! Tim kami siap membantu apapun untuk memajukan karirmu di era digital. Hubungi kami sekarang!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_hubungi_kami',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_hubungi_kami',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_blog',
                'value' => 'Blog',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Kelas
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_kelas',
                'value' => 'Kelas Terbaik untuk Karirmu',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_kelas',
                'value' => 'Temukan kelas-kelas digital terbaik untuk karirmu di SOC Media Academy. Bergabunglah sekarang dan kembangkan keterampilanmu di era digital!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_kelas',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_kelas',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Verifikasi Sertifikat
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_verifikasi_sertifikat',
                'value' => 'Verifikasi Sertifikat',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_verifikasi_sertifikat',
                'value' => 'Pastikan keaslian sertifikatmu dengan layanan verifikasi kami di SOC Media Academy. Percayakan masa depan karirmu pada sertifikasi digital yang sah.',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_verifikasi_sertifikat',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_verifikasi_sertifikat',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Kupon
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_kupon',
                'value' => 'Kupon',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_kupon',
                'value' => 'Hemat lebih banyak dengan kupon kami di SOC Media Academy! Segera manfaatkan penawaran istimewa ini untuk kelas-kelas digital terbaik!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_kupon',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_kupon',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Blog
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_blog',
                'value' => 'Blog',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_blog',
                'value' => 'Temukan tips, trik, dan wawasan terbaru di Blog SOC Media Academy. Dapatkan inspirasi dan pengetahuan untuk mengembangkan karirmu di dunia digital!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_blog',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_blog',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Blog
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_blog',
                'value' => 'Blog',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_blog',
                'value' => 'Temukan tips, trik, dan wawasan terbaru di Blog SOC Media Academy. Dapatkan inspirasi dan pengetahuan untuk mengembangkan karirmu di dunia digital!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_blog',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_blog',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // FAQ
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_faq',
                'value' => 'FAQ (Pertanyaan Umum)',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_faq',
                'value' => 'Dapatkan jawaban cepat di halaman FAQ SOC Media Academy. Temukan info penting tentang Online Course kami.',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_faq',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_faq',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],

            /**
             * REQUIRE AUTH
             */
            // Keranjang
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_keranjang',
                'value' => 'Keranjang Belanja',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_keranjang',
                'value' => 'Cek keranjang belanjamu di SOC Media Academy dan lanjutkan ke pembayaran. Dapatkan online course terbaik untuk menunjang karirmu sekarang!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_keranjang',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_keranjang',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Checkout
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_checkout',
                'value' => 'Selesaikan Pembelianmu',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_checkout',
                'value' => 'Lanjutkan ke proses checkout di SOC Media Academy dan dapatkan akses instan ke online course terbaik. Mulai perjalanan suksesmu hari ini!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_checkout',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_checkout',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],

            /**
             * CUSTOMER PANEL
             */
            // Dashboard
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_customer_dashboard',
                'value' => 'Dashboard',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_customer_dashboard',
                'value' => 'Kendalikan langkah-langkah karirmu dengan mudah di dashboard SOC Media Academy. Akses kursus, monitor progres, dan raih kesuksesan di dunia digital',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_customer_dashboard',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_customer_dashboard',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Notifikasi
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_customer_notifikasi',
                'value' => 'Notifikasi',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_customer_notifikasi',
                'value' => 'Periksa notifikasimu di SOC Media Academy untuk mendapatkan informasi terbaru tentang kursus dan penawaran spesial!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_customer_notifikasi',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_customer_notifikasi',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Kelas Saya
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_customer_kelas_saya',
                'value' => 'Kelas Saya',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_customer_kelas_saya',
                'value' => 'Temukan kelas yang kamu miliki disini. Mulailah belajar dan kembangkan karir digitalmu dengan mudah!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_customer_kelas_saya',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_customer_kelas_saya',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Profil
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_customer_profil',
                'value' => 'Profil Saya',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_customer_profil',
                'value' => 'Kelola informasi pribadi dan perjalanan karirmu di halaman profil SOC Media Academy. Tetap terhubung dan majukan dirimu di dunia digital!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_customer_profil',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_customer_profil',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Pesanan
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_customer_pesanan',
                'value' => 'Riwayat Pesanan',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_customer_pesanan',
                'value' => 'Lihat riwayat pesananmu di SOC Media Academy untuk melacak kursus yang sudah kamu beli. Tetap terorganisir dalam pengembangan karirmu!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_customer_pesanan',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_customer_pesanan',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],


            /**
             * AUTH PAGES
             */
            // Login
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_login',
                'value' => 'Login',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_login',
                'value' => 'Masuk ke SOC Media Academy untuk mengakses kelas online yang dapat menunjang skill-mu. Mulai karir suksesmu di dunia digital sekarang!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_login',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_login',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Register
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_register',
                'value' => 'Register',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_register',
                'value' => 'Daftar sekarang di SOC Media Academy untuk mengakses kelas online yang dapat menunjang skill-mu. Mulai karir suksesmu di dunia digital sekarang!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_register',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_register',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Forgot Password
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_forgot_password',
                'value' => 'Forgot Password',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_forgot_password',
                'value' => 'Pulihkan akses akunmu di SOC Media Academy dengan mudah. Reset password sekarang agar kamu bisa kembali menikmati layanan kami!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_forgot_password',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_forgot_password',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Reset Password
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_reset_password',
                'value' => 'Reset Password',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_reset_password',
                'value' => 'Pulihkan akses akunmu di SOC Media Academy dengan mudah. Reset password sekarang agar kamu bisa kembali menikmati layanan kami!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_reset_password',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_reset_password',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            // Verify Email
            [
                'group' => 'seo',
                'name' => 'Judul',
                'key' => 'seo_judul_verify_email',
                'value' => 'Verifikasi Email',
                'type' => 'input',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Deskripsi',
                'key' => 'seo_deskripsi_verify_email',
                'value' => 'Cek emailmu untuk verifikasi dan aktifkan akun SOC Media Academy. Langkah terakhir menuju akses ke online course terbaik!',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Gambar',
                'key' => 'seo_gambar_verify_email',
                'value' => '/assets/default/images/logo.png',
                'type' => 'image',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'group' => 'seo',
                'name' => 'Keyword',
                'key' => 'seo_keyword_verify_email',
                'value' => 'SOC Media Academy,SOC Media Group,SOC Software House,SOC Media Agency,Pelatihan digital,Karir digital,Kursus online,Skill digital,Belajar digital marketing,Beralih ke dunia digital,Pendidikan digital,Kursus profesional,Pelatihan untuk fresh graduates',
                'type' => 'textarea',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
        ];
    }
}
